name: Build and Test App
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up date and version
        id: vars
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          VERSION="v1.0.0"  # You can update this as needed, or fetch it from a version file
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/mdo-posts:${{ env.VERSION }}-${{ env.TIMESTAMP }}-${{ env.COMMIT_HASH }}
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/mdo-posts:${{ env.VERSION }}-${{ env.TIMESTAMP }}-${{ env.COMMIT_HASH }}
